name: Check some work has happened

on:
  pull_request:
    branches:
      - "main"

jobs:
  check-diff:
    name: Check diff size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Check that diff isn't too small"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILES_CHANGED=$(gh pr diff ${{github.event.pull_request.number}} --name-only | wc -l)
          COMMENT_BODY="Number of files changed in this PR: ${FILES_CHANGED}"
          
          if [ $FILES_CHANGED -ge 6 ]; then
            COMMENT_BODY="Number of files changed in this PR: ${FILES_CHANGED}. You've made a fair number of changes - good work! ðŸ˜Ž"
          else
            COMMENT_BODY="Number of files changed in this PR: ${FILES_CHANGED}. Looks like you've not answered some of the exercises."

          fi

          curl -s \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -X POST \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
